version: '3.8'

services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: laravel_app_prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    environment:
      - NODE_ENV=production

  web:
    image: nginx:latest
    container_name: laravel_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - laravel
